config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/index'
  root :to => 'welcome#index'
  
  resources :clientes do
   resources :facturas
   resources :personas
   resources :medios
  end

  resources :facturas
  resources :personas

   resources :facturas do
   resources :personas
  end

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :facturas, dependent: :restrict_with_error
	
	has_many :medios, dependent: :destroy
	validates :nombre,:apellido,:dni,:cuil_cuit,:direccion,:telefono, presence: {message:"Obligatorio"} 
	
	validates :nombre,:apellido,:direccion, length: {minimum: 3, maximum: 15, :message => "Entre 2 y 15 caracteres"}
	
	validates :dni,:telefono, numericality: {:only_integer => true,:greater_than_or_equal_to => 1, :message => "Debe ser numerico no negativo"}

	validates :dni,:cuil_cuit, uniqueness: { message: "Ya existe"}

	
	
	def edad
		age = Date.today.year - self.nacimiento.year
   		age = ((DateTime.now - self.nacimiento) / 365.25).to_i
	end

	def por_mes
		#a = Factura.where(cliente_id:self.id).group("emision") //agrupa por fecha exacta
		year=Date.today.year
		a= Factura.where(cliente_id:self.id).where("emision >= ? and emision <= ?", "#{year}-01-01", "#{year}-12-31").group("strftime('%m', emision)").count
	end

	def por_anio
		#b= Factura.where(cliente_id:self.id).group_by{|u| u.emision.year}
		b= Factura.where(cliente_id:self.id).group("strftime('%Y', emision)").sum("monto")
	end

	def mas_facturado
	#  personaas a las q mas cantidad de facturas le emitio
	#	d = Persona.includes(:facturas).where(facturas: { cliente_id: self.id }).group("persona_id").pluck("personas.nombre, count(facturas.id)").sort_by { |x| x[1] }.reverse.first(5) 
	d = Persona.includes(:facturas).where(facturas: { cliente_id: self.id }).group("persona_id").pluck("personas.nombre, sum(facturas.monto)").sort_by { |x| x[1] }.reverse.first(5) 
	end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @factura = Factura.new
    @persona = Persona.new
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    #@cliente.factura= @factura
    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'El cliente fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'El cliente fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    if ((@cliente.facturas.count > 0))
      respond_to do |format|
        format.html { redirect_to clientes_url, notice: 'El cliente tiene facturas,imposible eliminar.' }
        format.json { head :no_content }
      end
    else
      @cliente.destroy
      respond_to do |format|
        format.html { redirect_to clientes_url, notice: 'El cliente fue eliminado exitosamente.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido, :nacimiento, :genero, :dni, :cuil_cuit, :telefono, :email, :direccion)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :nacimiento %>
    <%= f.date_select :nacimiento, start_year:1940, end_year:2000 %>
  </div>
  <div class="field">
    <% sexo=["Masculino","Femenino"] %>
    <%= f.label :genero %>
    <%= f.select :genero,sexo %>
  </div>
  <div class="field">
    <%= f.label :dni %>
    <%= f.number_field :dni %>
  </div>
  <div class="field">
    <%= f.label :cuil_cuit %>
    <%= f.number_field :cuil_cuit %>
  </div>
  <div class="field">
    <%= f.label :telefono %>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>
<div id="bot">
<%= link_to 'Mostrar', @cliente %> | <%= link_to 'Volver', clientes_path %>	
</div>

<fieldset class="nuevo">
<%= render 'form' %>

          <h2>Medios Adicionales</h2>
              <% @cliente.medios.each do |medio| %>
		    <p>
		      <strong>Nombre:</strong>
		      <%= medio.nombre %>
		    </p>
		   
		    <p>
		      <strong>Contacto:</strong>
		      <%= medio.contacto %>
		    </p> 
			
			<%= link_to 'Eliminar', [medio.cliente, medio],
               method: :delete,
               data: { confirm: '¿Esta seguro?' } %>
		    <br>
		  <% end %>
         
          <%= form_for([@cliente, @cliente.medios.build]) do |f| %>
         
            <%= f.label :Medio %>
            <%= f.text_field :nombre %>
         
                    <%= f.label :contacto %>
            <%= f.text_field :contacto %>
          
          <p>
            <%= f.submit "Agregar Medio" %>
          </p>
        <% end %>

</fieldset>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nuestros Clientes</h1>
<div id="bot">
  <%= link_to 'Crear Cliente', new_cliente_path %>

</div>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nacimiento</th>
      <th>Genero</th>
      <th>Dni</th>
      <th>Cuil cuit</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.nacimiento %></td>
        <td><%= cliente.genero %></td>
        <td><%= cliente.dni %></td>
        <td><%= cliente.cuil_cuit %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.direccion %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clientes/new.html.erb
<h1>Agregar Cliente</h1>
<div id="bot">
	<%= link_to 'Volver', clientes_path %>	
</div>

<fieldset class="nuevo">

<%= render 'form' %>
</fieldset>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%= @cliente.nombre %> <%= @cliente.apellido %> </h1>

<div id="bot"> 
<%= link_to 'Editar', edit_cliente_path(@cliente) %> | <%= link_to 'Volver', clientes_path %>
</div>

<fieldset>
  <p>
    <strong>Nombre:</strong>
    <%= @cliente.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= @cliente.apellido %>
  </p>

  <p>
    <strong>Nacimiento:</strong>
    <%= @cliente.nacimiento %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= @cliente.genero %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= @cliente.dni %>
  </p>

  <p>
    <strong>Cuil cuit:</strong>
    <%= @cliente.cuil_cuit %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= @cliente.telefono %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @cliente.email %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= @cliente.direccion %>
  </p>

  <h3>Medios Adicionales</h3>
  
 <% if @cliente.medios.any? %>
      <% @cliente.medios.each do |medio| %>
      <p>
        <strong>Medio:</strong>
        <%= medio.nombre %>
      </p>
     
      <p>
        <strong>Contacto:</strong>
        <%= medio.contacto %>
      </p>
           <p style="color: grey" > <%= link_to 'Eliminar', [medio.cliente, medio],
               method: :delete,
               data: { confirm: '¿Esta seguro?' } %>
          </p>
      <br>
    <% end %>
  <% else %>
          <p>
            (El cliente no posee Medios Adicionales de comunicacion)
        </p>
  <% end%> 
       <%= form_for([@cliente, @cliente.medios.build]) do |f| %>
         
           <i style="color: grey"> <%= f.label :Medio %></i>
            <%= f.text_field :nombre %>
         
            <i style="color: grey"><%= f.label :contacto %></i>
            <%= f.text_field :contacto %>
          
          <p>
            <%= f.submit "Agregar Medio" %>
          </p>
        <% end %>

  <div>
    <h3>
      La edad del cliente es : <%= @cliente.edad %> 
    </h3>

   <% if @cliente.facturas.any? %>
      <h3>
        Total de Facturas Emitidas: <%= @cliente.facturas.count %>
      </h3>

       <h3>
            Facturacion por año: 
                <br>
                <% @cliente.por_anio.each do |x| %>
                * La facturacion en <%= x[0] %> fue de $:<%= x[1] %><br>
                <% end%>

        </h3>

        <h3>
            Cantidad de facturas por mes del corriente año: 
                <br>
                <% @meses=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"]%>
                <% @cliente.por_mes.each do |x| %>
                * Facturas emitidas el mes <%= @meses[x[0].to_i-1] %> fueron: <%= x[1]%><br>
                <% end%>
         
        </h3>

        <h3>
            Personas a las que mas facturo: <br>

              <% @cliente.mas_facturado.each do |x| %>
              * <%= x[0] %>:$<%= x[1] %><br>
              <% end%>
        </h3>
   <% else %>
        <h3>
            (El cliente no posee facturacion)
        </h3>
    <% end%> 
  </div>
</fieldset>


<div class="field">
  <h3>Ingrese nueva Factura</h3>
  <%= render "facturas/form"%>
</div>


<h3> Facturas del cliente</h3>
<table>
  <thead>
    <tr>
      <th>Monto</th>
      <th>Emision</th>
      <th>Descripcion</th> 
      <th>Entidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente.facturas.order(:emision).each do |factura| %>
      <tr>
        <td>$ <%= factura.monto %></td>
        <td><%= factura.emision %></td>
        <td><%= factura.descripcion %></td>
        <td><%= factura.persona.nombre %></td> 
        <td><%= link_to 'Ver', factura %></td>
        <td><%= link_to 'Editar', edit_factura_path(factura) %></td>
        <td><%= link_to 'Eliminar', factura, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>