config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/index'
  root :to => 'welcome#index'
  
  resources :clientes do
   resources :facturas
   resources :personas
   resources :medios
  end

  resources :facturas
  resources :personas

   resources :facturas do
   resources :personas
  end

end

app/models/factura.rb
class Factura < ActiveRecord::Base
	belongs_to :cliente
	belongs_to :persona

	validates :monto,:descripcion,:persona,:cliente, presence: {message:"Obligatorio"} 
	validates :monto, numericality: {:only_integer => true,:greater_than_or_equal_to => 1, :message => "Debe ser numerico no negativo"}

end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
    @personas = Persona.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
    @persona= Persona.new
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
    @factura.cliente = @cliente
    @factura.persona = @persona
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @cliente = Cliente.find(params[:cliente_id])
   # @persona = Persona.find(params[:persona_id])
    @factura = Factura.new(factura_params)
    @factura.cliente= @cliente
   
    
      respond_to do |format|
      if @factura.save
        format.html { redirect_to cliente_path(@cliente), notice: 'La factura fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @factura }
      else
        format.html { render :new }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    @cli= @factura.cliente

    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to cliente_path(@cli), notice: 'La factura fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @factura }
      else
        format.html { render :edit }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @cli= @factura.cliente
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to @cli, notice: 'La factura fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:monto, :emision, :descripcion, :persona_id)
    end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= form_for([@cliente,@factura]) do |f| %>
  <% if @factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factura.errors.count, "error") %> prohibited this factura from being saved:</h2>

      <ul>
      <% @factura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="nuevo">
    
    <div class="field">
      <%= f.label :persona %>/Entidad:
      <%= collection_select( :factura, :persona_id, Persona.all, :id,:nombre) %>
   
       <%= link_to 'Agregar Entidad', new_persona_path %>
 </div>

    <div class="field">
      <%= f.label :monto %> $ : <%= f.text_field :monto %>
    </div>
    <br>
    <div class="field">
      <%= f.label :emision %>
      <%= f.date_select :emision %>
    </div>
    <div class="field">
      <%= f.label :descripcion %>
      <%= f.text_area :descripcion %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/facturas/edit.html.erb
<h1>Editar Factura</h1>
<div id="bot">

<%= link_to 'Mostrar', @factura %> | <%= link_to 'Volver', cliente_path %>
	
</div>
<%= render 'form' %>

app/views/facturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todas las Facturas del Sistema</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Monto</th>
      <th>Emision</th>
      <th>Descripcion</th>
      <th>Emitida a:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.cliente.nombre %></td>   
        <td>$ <%= factura.monto %></td>
        <td><%= factura.emision %></td>
        <td><%= factura.descripcion %></td>
        <td><%= factura.persona.nombre %></td>

        <td><%= link_to 'Mostrar', factura %></td>
        <td><%= link_to 'Editar', edit_factura_path(factura) %></td>
        <td><%= link_to 'Eliminar', factura, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/facturas/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Factura emitida a: <%= @factura.cliente.nombre %> <%= @factura.cliente.apellido %> </h1>

<div id="bot">
<%= link_to 'Editar', edit_factura_path(@factura) %> | <%= link_to 'Volver', cliente_path %>
<div>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Monto</th>
      <th>Emision</th>
      <th>Descripcion</th>
      <th>Emitida a:</th>
    </tr>
  </thead>

  <tbody>
  
      <tr>

        <td><%= @factura.cliente.nombre %> <%= @factura.cliente.apellido %></td>   
        <td><%= @factura.monto %></td>
        <td><%= @factura.emision %></td>
        <td><%= @factura.descripcion %></td>
        <td><%= @factura.persona.nombre %></td>   

      </tr>
 
  </tbody>
</table>