config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/index'
  root :to => 'welcome#index'
  
  resources :clientes do
   resources :facturas
   resources :personas
   resources :medios
  end

  resources :facturas
  resources :personas

   resources :facturas do
   resources :personas
  end

end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_many :facturas
	validates :nombre,:descripcion, presence: {message:"Obligatorio"} 
	validates :nombre, length: {minimum: 3, maximum: 25, :message => "Entre 2 y 25 caracteres"}

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @factura = Factura.new
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)
   
    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'La Persona/Entidad fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'La Persona fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    if ((@persona.facturas.count > 0))
      respond_to do |format|
        format.html { redirect_to personas_url, notice: 'La Persona posee facturacion,imposible eliminar' }
        format.json { head :no_content }
      end
    else
      @persona.destroy
      respond_to do |format|
        format.html { redirect_to personas_url, notice: 'La Persona fue eliminada exitosamente' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :descripcion)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>:
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %>:
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editar Persona</h1>

<div id="bot">

<%= link_to 'Mostrar', @persona %> | <%= link_to 'Volver', personas_path %>
	
</div>

<fieldset class="nuevo">
	<%= render 'form' %>
</fieldset>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Entidades/Personas</h1>
<div id="bot">
  <%= link_to 'Agregar Persona', new_persona_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.descripcion %></td>
        <td><%= link_to 'Mostrar', persona %></td>
        <td><%= link_to 'Editar', edit_persona_path(persona) %></td>
        <td><%= link_to 'Eliminar', persona, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/personas/new.html.erb
<h1>Agregar Persona</h1>


<div id="bot">
	<%= link_to 'Volver', personas_path %>
</div>

<fieldset class="nuevo">
	
<%= render 'form' %>
</fieldset>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Entidad: <%= @persona.nombre %></h1>


<div id="bot">

<%= link_to 'Editar', edit_persona_path(@persona) %> | <%= link_to 'Volver', personas_path %>
	
</div>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>

    </tr>
  </thead>

  <tbody>
  
      <tr>
        <td><%= @persona.nombre %></td>   
        <td><%= @persona.descripcion %></td>
      </tr>
 
  </tbody>
</table>